name: c2c_kit_flutter
description: Shared C2C Flutter kit — auth API, models, and common UI building blocks.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  http: ^1.6.0
  pin_code_fields: ^9.4.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/
